spring:
  application:
    name: ms-user
  jackson:
    default-property-inclusion: non_null
  jpa:
    ##defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create
    ##open-in-view: false
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:~/smartjob
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
server:
  port: 8081
  servlet:
    context-path: /smartjob/api/v1
logging:
  level:
    org.hibernate.SQL: debug